(display "argv: ")
(display (vector-length *argv*))
(newline)
(let loop ((i 0))
  (if (>= i (vector-length *argv*))
      (newline)
      (begin (display i)
             (display " ")
             (if (= i 0)
                 (begin (display "<file-exists?> ")
                        (display (not (not (stat (vector-ref *argv* 0))))))
                 (display (vector-ref *argv* i)))
             (newline)
             (loop (+ i 1)))))
