(define f (open-input-file "tests/inputfile.scm"))
(display (input-port? f))
(newline)
(define c (read-char f))
(display c)
(newline)
(display (eof-object? c))
(newline)
(let loop ((c (read-char f)))
  (if (eof-object? c)
      (begin (display 'done)
             (newline))
      (begin (display c)
             (loop (read-char f)))))
(close-input-port f)
(display 'closed)
(newline)
