(define c (new-counter))
(display "new-counter done")
(newline)
(display (inc-counter c))
(newline)
(display (inc-counter c))
(newline)
(display (inc-counter c))
(newline)
(display (inc-counter c))
(newline)
(display (inc-counter c))
(newline)
(display (inc-counter c))
(newline)
(display (inc-counter c))
(newline)
(display (inc-counter c))
(newline)
(display (inc-counter c))
(newline)
(display (inc-counter c))
(newline)
(display (inc-counter c))
(newline)
(display (inc-counter c))
(newline)
(display (inc-counter c))
(newline)
(display (inc-counter c))
(newline)
(display (inc-counter c))
(newline)
