(define x (make-vector 20 #f))
(display (vector? x))
(newline)
(let loop ((i 0))
  (if (< i (vector-length x))
      (begin (display (vector-ref x i))
             (vector-set! x i i)
             (loop (+ i 1)))
      (begin (display i)
             (newline))))
(display x)
(newline)
(set! x (make-vector 20))
(display (vector? x))
(newline)
(display x)
(newline)
(let loop ((i 0))
  (if (< i (vector-length x))
      (begin (display (vector-ref x i))
             (vector-set! x i i)
             (loop (+ i 1)))
      (begin (display i)
             (newline))))
(display x)
(newline)
