(display (= (quotient 13 4) 3))
(newline)
(display (= (modulo 13 4) 1))
(newline)
(display (= (remainder 13 4) 1))
(newline)

(display (= (quotient -13 4) -3))
(newline)
(display (= (modulo -13 4) 3))
(newline)
(display (= (remainder -13 4) -1))
(newline)

(display (= (quotient 13 -4) -3))
(newline)
(display (= (modulo 13 -4) -3))
(newline)
(display (= (remainder 13 -4) 1))
(newline)

(display (= (quotient -13 -4) 3))
(newline)
(display (= (modulo -13 -4) -1))
(newline)
(display (= (remainder -13 -4) -1))
(newline)
