(define test-case-number 0)
(define-syntax test
  (syntax-rules ()
    ((_ expression)
     (begin (set! test-case-number (+ test-case-number 1))
            (display "case ")
            (display test-case-number)
            (display ": ")
            (newline)
            (display 'expression)
            (display " => ")
            (display expression)
            (newline)
            (newline)))))

(test (+ 3))
(test (+ 1 2))
(test (+ 1 1 1 1 1 1 1))
(test (+ 1000 10))
(test (+ -31459))
(test (+ 40 10 10 10 10 10 -10))
