(define f (open-output-file (vector-ref *argv* 1)))
(display (output-port? f) (current-output-port))
(newline (current-output-port))
(display "foo" f)
(newline f)
(display 3 f)
(newline f)
(close-output-port f)
(display 'closed (current-output-port))
(newline (current-output-port))
