(define f (open-input-file "tests/read-dat.scm"))
(let loop ((c (peek-char f)))
  (let ((c1 (peek-char f)))
    (if (eof-object? c)
        (begin (if (not (eq? c c1))
                   (error "eof-object not equal"))
               (display (eof-object? c))
               (newline))
        (begin (if (not (char=? c c1))
                   (error "peek-char not equal"))
               (let ((c2 (read-char f)))
                 (if (not (char=? c2 c))
                     (error "read-char and peek-char not equal"))
                 (display c2)
                 (loop (peek-char f)))))))
(close-input-port f)
