(write-char (if (string? "asdf") #\y #\n))
(write-char (if (number? 3) #\y #\n))
(write-char (if (number? "asdf") #\y #\n))
(write-char (if (string? 3) #\y #\n))
(newline)
(write-char (if (procedure? procedure?) #\y #\n))
(write-char (if (procedure? #\a) #\y #\n))
(write-char (if (procedure? "asdf") #\y #\n))
(write-char (if (procedure? write-char) #\y #\n))
(newline)
