(define f (open-input-file "tests/read-dat.scm"))
(display (input-port? f))
(newline)
(define c1 (peek-char f))
(display c1)
(newline)
(set! c1 (peek-char f))
(display c1)
(newline)
(set! c1 (peek-char f))
(display c1)
(newline)
(set! c1 (read-char f))
(display c1)
(newline)
(set! c1 (read-char f))
(display c1)
(newline)
(set! c1 (read-char f))
(display c1)
(newline)
(set! c1 (read-char f))
(display c1)
(newline)
(set! c1 (read-char f))
(display c1)
(newline)
(set! c1 (read-char f))
(display c1)
(newline)
(set! c1 (read-char f))
(display c1)
(newline)
(set! c1 (read-char f))
(display c1)
(newline)
(set! c1 (read-char f))
(display c1)
(newline)
(set! c1 (read-char f))
(display (eof-object? c1))
(newline)
(close-input-port f)
(display 'done)
(newline)
