(need util/list)
(need pat/pat)
(need sasm/sasm-insn)
(define (test-exp-linkage req given link)
  (display-insn-seq (with-expression-linkage (empty-insn-seq)
                                             req
                                             given
                                             link)))
(display "case 1\n")
(test-exp-linkage (register-target 'accum)
                  (make-target '(local 0))
                  (return-linkage 0))
(display "\ncase 2\n")
(test-exp-linkage (register-target 'accum)
                  (register-target 'accum)
                  (next-linkage))
(display "\ncase 3\n")
(test-exp-linkage (register-target 'operand)
                  (register-target 'accum)
                  (goto-linkage 'foobar))
(display "\ncase 4\n")
(test-exp-linkage (register-target 'accum)
                  (make-target '(arg 2))
                  (goto-linkage 'foobar))
