(define (sum a b)
  (define (iter sum a)
    (if (> a b)
        sum
        (iter (+ sum a) (+ a 1))))
  (iter 0 a))

(define (bi b)
  (if b 1 0))

(define (fact x)
  (if (= x 0)
      1
      (* x (fact (- x 1)))))

(display (sum 1 3))
(newline)
(display (+ 1 1))
(newline)
(display (+ 1 2))
(newline)
(display (+ 1 2 3))
(newline)
(display (bi (< 1 2)))
(newline)
(display (bi (< 2 1)))
(newline)
(display (string->number "120"))
(newline)
(display (string->number "-120"))
(newline)
(display (string->number "0000000"))
(newline)
(display (string->number "12345"))
(newline)
(display (- 1 2 3))
(newline)
(display (* 3 5))
(newline)
(display (fact 0))
(newline)
(display (fact 1))
(newline)
(display (fact 2))
(newline)
(display (fact 3))
(newline)
(display (fact 4))
(newline)
(display (fact 5))
(newline)
(display (fact 10))
(newline)
(display (string->number "3628800"))
(newline)
