(define (nasm-x86-machine-base)
  (append
   (nasm-x86-interp-support)
   (nasm-x86-machine-labels)
   (nasm-x86-control)
   (nasm-x86-compare)
   (nasm-x86-stack)
   (nasm-x86-store-array)
   (nasm-x86-load-array)
   (nasm-x86-call)
   (nasm-x86-return)
   (nasm-x86-arithmetic)
   (nasm-x86-multiply)
   (nasm-x86-bitwise-const)
   (nasm-x86-rshift)
   (nasm-x86-data)
   (nasm-x86-preamble)
   (nasm-x86-debug)
   ))

