(define (nasm-x64-machine-base)
  (append
   (nasm-x64-interp-support)
   (nasm-x64-machine-labels)
   (nasm-x64-control)
   (nasm-x64-compare)
   (nasm-x64-stack)
   (nasm-x64-store-array)
   (nasm-x64-load-array)
   (nasm-x64-call)
   (nasm-x64-return)
   (nasm-x64-arithmetic)
   (nasm-x64-multiply)
   (nasm-x64-bitwise-const)
   (nasm-x64-rshift)
   (nasm-x64-data)
   (nasm-x64-preamble)
   (nasm-x64-debug)
   ))

