(define (scheme-codegen-continue-with-tail-call-varargs n-args-out)
  (define (repeat-copy-arg times)
    (if (zero? times)
        (empty-insn-seq)
        (append-insn-seq
         (insn-seq '(accum)
                   '(accum index)
                   `((assign (reg index) (op load-array)
                             (reg accum) (const 0))
                     (push (reg index))
                     ,@(if (> times 1)
                           '((assign (reg accum) (op sub-pointer)
                                     (reg accum) (const 1)))
                           '())))
         (repeat-copy-arg (- times 1)))))
  (append-insn-seq
   (insn-seq `(,(cadr (link-register)))
             '(accum)
             `((assign (reg accum) (op add-pointer) (sys stack-pointer)
                       (const ,(- n-args-out 1)))
               (perform (op pop-frame))
               (pop (reg index))
               (assign (reg index) (op bit-lshift) (reg index)
                       (symconst shift-cells-per-word))
               (assign (sys stack-pointer) (op add) (sys stack-pointer)
                       (reg index))))
   (repeat-copy-arg n-args-out)
   (insn-seq `(,(cadr (link-register)) ,(cadr (env-register)))
             '() ;; all registers will be modified, but since this is a tail call it doesn't matter
             `((assign (reg index) (const ,n-args-out))
               (goto (reg operand))))))

