POSITIVE_SCHEME_TESTS=\
  out/$(TEST_OUTDIR_NAME)/test/apply.sasm \
  out/$(TEST_OUTDIR_NAME)/test/apply.sasm-opt \
  out/$(TEST_OUTDIR_NAME)/test/apply.asm \
  out/$(TEST_OUTDIR_NAME)/test/apply.out \
  out/$(TEST_OUTDIR_NAME)/test/apply.diff \
  out/$(TEST_OUTDIR_NAME)/test/cseconds.out \
  out/$(TEST_OUTDIR_NAME)/test/disptest.out \
  out/$(TEST_OUTDIR_NAME)/test/disptest.diff \
  out/$(TEST_OUTDIR_NAME)/test/disptest2.out \
  out/$(TEST_OUTDIR_NAME)/test/disptest2.diff \
  out/$(TEST_OUTDIR_NAME)/test/argv.out \
  out/$(TEST_OUTDIR_NAME)/test/argv.diff \
  out/$(TEST_OUTDIR_NAME)/test/rename.out \
  out/$(TEST_OUTDIR_NAME)/test/rename.diff \
  out/$(TEST_OUTDIR_NAME)/test/delete.out \
  out/$(TEST_OUTDIR_NAME)/test/delete.diff \
  out/$(TEST_OUTDIR_NAME)/test/stat.out \
  out/$(TEST_OUTDIR_NAME)/test/stat.diff \
  out/$(TEST_OUTDIR_NAME)/test/getenv.out \
  out/$(TEST_OUTDIR_NAME)/test/getenv.diff \
  out/$(TEST_OUTDIR_NAME)/test/outputfile.out \
  out/$(TEST_OUTDIR_NAME)/test/outputfile.diff \
  out/$(TEST_OUTDIR_NAME)/test/inputfile.out \
  out/$(TEST_OUTDIR_NAME)/test/inputfile.diff \
  out/$(TEST_OUTDIR_NAME)/test/read.out \
  out/$(TEST_OUTDIR_NAME)/test/read.diff \
  out/$(TEST_OUTDIR_NAME)/test/read2.out \
  out/$(TEST_OUTDIR_NAME)/test/read2.diff \
  out/$(TEST_OUTDIR_NAME)/test/read3.out \
  out/$(TEST_OUTDIR_NAME)/test/read3.diff \
  out/$(TEST_OUTDIR_NAME)/test/peekchar.out \
  out/$(TEST_OUTDIR_NAME)/test/peekchar.diff \
  out/$(TEST_OUTDIR_NAME)/test/mkvec.out \
  out/$(TEST_OUTDIR_NAME)/test/mkvec.diff \
  out/$(TEST_OUTDIR_NAME)/test/eqv.out \
  out/$(TEST_OUTDIR_NAME)/test/eqv.diff \
  out/$(TEST_OUTDIR_NAME)/test/eq.out \
  out/$(TEST_OUTDIR_NAME)/test/eq.diff \
  out/$(TEST_OUTDIR_NAME)/test/vararg.out \
  out/$(TEST_OUTDIR_NAME)/test/vararg.diff \
  out/$(TEST_OUTDIR_NAME)/test/read4.out \
  out/$(TEST_OUTDIR_NAME)/test/read4.diff \
  out/$(TEST_OUTDIR_NAME)/test/read5.out \
  out/$(TEST_OUTDIR_NAME)/test/read5.diff \
  out/$(TEST_OUTDIR_NAME)/test/sym1.out \
  out/$(TEST_OUTDIR_NAME)/test/sym1.diff \
  out/$(TEST_OUTDIR_NAME)/test/opeq.out \
  out/$(TEST_OUTDIR_NAME)/test/opeq.diff \
  out/$(TEST_OUTDIR_NAME)/test/opminus.out \
  out/$(TEST_OUTDIR_NAME)/test/opminus.diff \
  out/$(TEST_OUTDIR_NAME)/test/opplus.out \
  out/$(TEST_OUTDIR_NAME)/test/opplus.diff \
  out/$(TEST_OUTDIR_NAME)/test/opgt.out \
  out/$(TEST_OUTDIR_NAME)/test/opgt.diff \
  out/$(TEST_OUTDIR_NAME)/test/oplt.out \
  out/$(TEST_OUTDIR_NAME)/test/oplt.diff \
  out/$(TEST_OUTDIR_NAME)/test/opmul.out \
  out/$(TEST_OUTDIR_NAME)/test/opmul.diff \
  out/$(TEST_OUTDIR_NAME)/test/pair.out \
  out/$(TEST_OUTDIR_NAME)/test/pair.diff \
  out/$(TEST_OUTDIR_NAME)/test/mkstring.out \
  out/$(TEST_OUTDIR_NAME)/test/mkstring.diff \
  out/$(TEST_OUTDIR_NAME)/test/str2num.out \
  out/$(TEST_OUTDIR_NAME)/test/str2num.diff \
  out/$(TEST_OUTDIR_NAME)/test/opdiv.out \
  out/$(TEST_OUTDIR_NAME)/test/opdiv.diff \
  out/$(TEST_OUTDIR_NAME)/test/char.out \
  out/$(TEST_OUTDIR_NAME)/test/char.diff \
  out/$(TEST_OUTDIR_NAME)/test/pred.out \
  out/$(TEST_OUTDIR_NAME)/test/pred.diff \
  out/$(TEST_OUTDIR_NAME)/test/write.out \
  out/$(TEST_OUTDIR_NAME)/test/write.diff \
  out/$(TEST_OUTDIR_NAME)/test/equal.out \
  out/$(TEST_OUTDIR_NAME)/test/equal.diff \
  out/$(TEST_OUTDIR_NAME)/test/r5rs1.out \
  out/$(TEST_OUTDIR_NAME)/test/r5rs1.diff \
  out/$(TEST_OUTDIR_NAME)/test/r5rs2.out \
  out/$(TEST_OUTDIR_NAME)/test/r5rs2.diff \
  out/$(TEST_OUTDIR_NAME)/test/r5rs3.out \
  out/$(TEST_OUTDIR_NAME)/test/r5rs3.diff \
  out/$(TEST_OUTDIR_NAME)/test/char-case.out \
  out/$(TEST_OUTDIR_NAME)/test/char-case.diff \
  out/$(TEST_OUTDIR_NAME)/test/read6.out \
  out/$(TEST_OUTDIR_NAME)/test/read6.diff \
  out/$(TEST_OUTDIR_NAME)/test/str2num2.out \
  out/$(TEST_OUTDIR_NAME)/test/str2num2.diff \
  out/$(TEST_OUTDIR_NAME)/test/num2str.out \
  out/$(TEST_OUTDIR_NAME)/test/num2str.diff \
  out/$(TEST_OUTDIR_NAME)/test/set1.out \
  out/$(TEST_OUTDIR_NAME)/test/set1.diff \
  out/$(TEST_OUTDIR_NAME)/test/read7.out \
  out/$(TEST_OUTDIR_NAME)/test/read7.diff \
  out/$(TEST_OUTDIR_NAME)/test/read8.out \
  out/$(TEST_OUTDIR_NAME)/test/read8.diff \
  out/$(TEST_OUTDIR_NAME)/test/strref.out \
  out/$(TEST_OUTDIR_NAME)/test/strref.diff \
  out/$(TEST_OUTDIR_NAME)/test/string.out \
  out/$(TEST_OUTDIR_NAME)/test/string.diff \
  out/$(TEST_OUTDIR_NAME)/test/string2.out \
  out/$(TEST_OUTDIR_NAME)/test/string2.diff \
  out/$(TEST_OUTDIR_NAME)/test/string3.out \
  out/$(TEST_OUTDIR_NAME)/test/string3.diff \
  out/$(TEST_OUTDIR_NAME)/test/stringset.out \
  out/$(TEST_OUTDIR_NAME)/test/stringset.diff \
  out/$(TEST_OUTDIR_NAME)/test/order-eval.out \
  out/$(TEST_OUTDIR_NAME)/test/order-eval.diff \
  out/$(TEST_OUTDIR_NAME)/test/read9.out \
  out/$(TEST_OUTDIR_NAME)/test/read9.diff \
  out/$(TEST_OUTDIR_NAME)/test/read10.out \
  out/$(TEST_OUTDIR_NAME)/test/read10.diff \
  out/$(TEST_OUTDIR_NAME)/test/read11.out \
  out/$(TEST_OUTDIR_NAME)/test/read11.diff


NEGATIVE_SCHEME_TESTS=\
  out/$(TEST_OUTDIR_NAME)/test/badapply.out \
  out/$(TEST_OUTDIR_NAME)/test/badapply.diff \
  out/$(TEST_OUTDIR_NAME)/test/badvrhi.out \
  out/$(TEST_OUTDIR_NAME)/test/badvrhi.diff \
  out/$(TEST_OUTDIR_NAME)/test/badvrlo.out \
  out/$(TEST_OUTDIR_NAME)/test/badvrlo.diff \
  out/$(TEST_OUTDIR_NAME)/test/badvshi.out \
  out/$(TEST_OUTDIR_NAME)/test/badvshi.diff \
  out/$(TEST_OUTDIR_NAME)/test/badvslo.out \
  out/$(TEST_OUTDIR_NAME)/test/badvslo.diff \
  out/$(TEST_OUTDIR_NAME)/test/badsrhi.out \
  out/$(TEST_OUTDIR_NAME)/test/badsrhi.diff \
  out/$(TEST_OUTDIR_NAME)/test/badsrlo.out \
  out/$(TEST_OUTDIR_NAME)/test/badsrlo.diff \
  out/$(TEST_OUTDIR_NAME)/test/badsshi.out \
  out/$(TEST_OUTDIR_NAME)/test/badsshi.diff \
  out/$(TEST_OUTDIR_NAME)/test/badsslo.out \
  out/$(TEST_OUTDIR_NAME)/test/badsslo.diff \
  out/$(TEST_OUTDIR_NAME)/test/gc1.out

ALL_SCHEME_TESTS=\
  $(POSITIVE_SCHEME_TESTS) \
  $(NEGATIVE_SCHEME_TESTS)
